
logging:
  level:
    org:
      springframework: debug
spring:
  application:
    name: elevatemart-api-gateway
  zipkin:
    base-url: http://localhost:9411/

server:
  port: 9099
eureka:
  client:
    register-with-eureka: false

