
logging:
  pattern:
    level: "%5p [${spring.application.name},%X{traceId:-},%X{spanId:-}]"

spring:
  application:
    name: elevatemart-api-gateway
  zipkin:
    base-url: http://localhost:9411/
  sleuth:
    sampler:
      probability: 1.0
  cloud:
    gateway:
      discovery:
        locator:
          enable: true

server:
  port: 9099
eureka:
  client:
    register-with-eureka: true
